import { Inter } from 'next/font/google'
import "./styles/globals.scss";

const inter = Inter({ subsets: ['latin'], weight:['100','400', '500', '600', '700'] })



export const metadata = {
  title: 'MBF Design',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
